[preprocessor/folder] handle proofmode bundle in folder preprocessor
starlinglab/integrity-v2 pull request #18
Opened 2024-06-01 17:19 UTC by williamchong

- support parsing of proofmode zip json
- support parsing of multiple asset json in proofmode
- verify asset signature, csv and json signature with gpg
- support cbor in webhook client and server as metadata format

2024-06-10 13:50 UTC, makew0rld requested changes

2024-06-10 13:50 UTC, makew0rld commented on preprocessor/folder/file.go
> +	mediaType := "application/zip"
The Proofmode ZIP is just a container, sometimes for multiple assets. Since we extract and separate these assets, the `media_type` attestation that gets stored should be the actual media type of the specific asset, like `image/jpeg`. This can be determined from the magic bytes of the file like what happens normally.

2024-06-10 13:50 UTC, makew0rld commented on preprocessor/folder/file.go
> +			"asset_signature": hex.EncodeToString(asset.AssetSignature),
According to #3 this should be `asset_origin_signature`. I also don't think it need to be hex-encoded, as I believe Proofmode signature files are just text.

2024-06-10 13:50 UTC, makew0rld commented on preprocessor/folder/file.go
> +func checkFileType(filePath string) (string, string, error) {
Could use documentation.

2024-06-10 13:50 UTC, makew0rld commented on util/proofmode.go
> +package util
This whole file does not belong in `util/` in my opinion. `util` is for shared utility functions, that are useful in many different places. This is only useful in one place and should probably just be under `preprocessor/folder/`.

2024-06-10 13:50 UTC, makew0rld commented on util/proofmode.go
> +	"golang.org/x/crypto/openpgp" // nolint:staticcheck
This package is deprecated and unmaintained, see [this issue](https://github.com/golang/go/issues/44226). Please use [this](https://github.com/ProtonMail/go-crypto) reputable community fork instead, it's a drop-in replacement.

2024-06-10 13:50 UTC, makew0rld commented on util/proofmode.go
> +	keyRing, err := openpgp.ReadArmoredKeyRing(bytes.NewReader(keyFileBytes))
In future PRs this key will need to be checked against the database of good keys, see #25

2024-06-10 13:50 UTC, makew0rld commented on util/proofmode.go
> +	assetFileReader = io.TeeReader(assetFileReader, blake)
Use a single `io.TeeReader` with an `io.MultiWriter` as the writer.

2024-06-10 13:50 UTC, makew0rld commented on util/proofmode.go
> +func parseProofModeBundleAssetInfo(zipReader *zip.ReadCloser) (map[string]*zip.File, [][]byte, error) {
Some documentation here would be helpful.

2024-06-10 13:50 UTC, makew0rld commented on util/proofmode.go
> +func GetProofModeZipFiles(zipListing *zip.ReadCloser) (map[string]*zip.File, [][]byte, error) {
Documentation

2024-06-11 10:05 UTC, williamchong commented on util/proofmode.go
> +package util
proofmode parsing can be used in say signal bot in the future though, should it be in `preprocessor` in this case?

2024-06-11 14:28 UTC, makew0rld commented on util/proofmode.go
> +package util
Ah, good point. Okay, let's put it in its own package like `preprocessor/proofmode`. Then you can update some function names to not include `proofmode` in them as well perhaps.

2024-06-11 14:29 UTC, makew0rld commented
I've responded to a comment above, but also note this will need updating in reference to the latest [issue 3 updates](https://github.com/starlinglab/integrity-v2/issues/3#issuecomment-2160810593) and

2024-06-11 15:28 UTC, williamchong commented on util/proofmode.go
> +package util
https://github.com/starlinglab/integrity-v2/pull/18/commits/4f0d8b1228f6b0d14cb7f6ef7fa717a089cb1028

2024-06-11 15:44 UTC, makew0rld approved these changes
Looks good to me, just see some small comments below.

2024-06-11 15:44 UTC, makew0rld commented on preprocessor/folder/file.go
> +				"gst":       asset.Gst,
`pubkey` and `gst` are also naturally strings right? We could store them that way.

2024-06-11 15:44 UTC, makew0rld commented on preprocessor/folder/file.go
> +	if project != nil {
When would `project` be `nil`? Should that be an error?

2024-06-11 15:44 UTC, makew0rld commented on preprocessor/proofmode/proofmode.go
> +	}
Don't forget to close the file.

2024-06-11 15:44 UTC, makew0rld commented on preprocessor/proofmode/proofmode.go
> +	fileMap, jsonFilesBytes, err := GetMapOfZipFiles(zipListing)
All these open files in `fileMap` should be closed, ideally. Also in other places where the file map is used.

2024-06-11 17:19 UTC, williamchong commented on preprocessor/proofmode/proofmode.go
> +	fileMap, jsonFilesBytes, err := GetMapOfZipFiles(zipListing)
Yes we would still need to call`.Open()` when using the file map, so each `.Open()` is paired with `.Close()` then it should be fine

2024-06-11 17:21 UTC, williamchong commented on preprocessor/folder/file.go
> +	if project != nil {
Yes should have just throw in the beginning of function

2024-06-11 17:37 UTC, makew0rld approved these changes

2024-06-11 17:40 UTC, merged