[webhook] generate encKey for private fields
starlinglab/integrity-v2 pull request #23
Opened 2024-06-09 09:32 UTC by williamchong

Fixes https://github.com/starlinglab/integrity-v2/issues/21

2024-06-10 14:08 UTC, makew0rld requested changes
I am not sure making a function in `genkey/` is the way to do this. Perhaps it should be extracted into `util/` instead, or its own module.

2024-06-11 09:18 UTC, williamchong commented on webhook/attribute.go
> +					return nil, fmt.Errorf("error reading key: %w", err)
Would it be appropriate for genkey cli to also reuse existing key, or should we keep throwing error?

2024-06-11 14:17 UTC, makew0rld commented on webhook/attribute.go
> +					return nil, fmt.Errorf("error reading key: %w", err)
The semantics are different. `genkey` is used to generate a key, so if a key already exists it should throw an error because this is probably unexpected. The user can then choose what to do, likely they will ignore the error and be happy to use the existing key.

In this case, an existing key isn't an error, it's totally possible for that to happen, so the code should just continue.

2024-06-11 15:52 UTC, makew0rld approved these changes

2024-06-11 15:53 UTC, merged