[preprocessor/wacz] add wacz user agent
starlinglab/integrity-v2 pull request #39
Opened 2024-06-13 17:25 UTC by williamchong

Fix https://github.com/starlinglab/integrity-v2/issues/13

2024-06-13 19:01 UTC, makew0rld requested changes
This code will fail with WACZ files from Browsertrix, please test with those. For example `archive/data.warc.gz` is not guaranteed to exist. Looking at the [spec](https://specs.webrecorder.net/wacz/1.1.1/#archive), it seems you should be looking for any `.warc` or `.warc.gz` file in `archive/`.

2024-06-16 18:24 UTC, williamchong commented
rewrote the logic, also switched to use `ReadString` to avoid buffer full error stopping the scan too early

2024-06-17 13:55 UTC, makew0rld requested changes
This looks good other than one memory issue I've mentioned below.

2024-06-17 13:56 UTC, makew0rld commented on preprocessor/wacz/wacz.go
> +		line, err := reader.ReadString('\n')
After reading the docs and stdlib source code, I think there is a problem with using this function. It seems it will load the entire line into memory, even if it exceeds the buffer size of the `reader`. This could be a problem in cases where the WARC record you are reading contains some large file (like a video) that doesn't include a newline character for a while.

I think the better function to use would be the low-level `ReadLine`. That function allows you to know when lines are larger than your buffer, and skip past them. For an example how of how to do this, see https://github.com/kevinburke/sll/blob/master/sll.go#L48.

2024-06-17 14:41 UTC, williamchong commented on preprocessor/wacz/wacz.go
> +		line, err := reader.ReadString('\n')
Updated to use `ReadLine`

2024-06-17 14:44 UTC, makew0rld approved these changes
Thanks!

2024-06-17 14:44 UTC, merged