[preprocessor/webhook] add browsertrix cloud webhook
starlinglab/integrity-v2 pull request #44
Opened 2024-06-17 18:42 UTC by williamchong

Fixes https://github.com/starlinglab/integrity-v2/issues/33

TODO:
docs

2024-06-18 13:49 UTC, makew0rld requested changes
Besides docs, I see two things missing here:
- Validation of metadata: Browsertrix gives us a file size and hash, and we should check that they match our calculations.
- Authentication: the `/browsertrix` route is open to anyone. Since we can't give them a JWT to use, instead we should secure the route by having a secret in the query string. That secret can be defined in the config.

Auth example: `/browsertrix?s=wzfo63r2focmt6fw`

2024-06-18 13:49 UTC, makew0rld commented on webhook/browsertrix.go
> +		writeJsonResponse(w, http.StatusOK, map[string]string{})
Return JSON is unnecessary here, you can just use `w.WriteHeader(http.StatusOk)`.

2024-06-18 13:49 UTC, makew0rld commented on webhook/browsertrix.go
> +	writeJsonResponse(w, http.StatusOK, map[string]string{"cid": cid})
Why tell Browsertrix the CID?

2024-06-18 13:49 UTC, makew0rld commented on webhook/browsertrix.go
> +	jwtToken, err := getJWTToken()
Ideally we wouldn't be logging in each time. The returned JWT token should have an expiry date embedded in it, and `getJWTToken` could cache and re-use it until it expires.

2024-06-18 20:31 UTC, makew0rld requested changes

2024-06-18 20:31 UTC, makew0rld commented on webhook/browsertrix.go
> +	browsertrixJwtMutex.Unlock()
In all the cases where there are errors, this mutex is never unlocked. The idiomatic way of doing this in Go is to `defer` your `Unlock` right after calling `Lock`.

2024-06-18 21:00 UTC, williamchong commented
It seems browsertrix gives a new cert every time i try, not sure if we should just trust all cert sha for now

2024-06-19 14:46 UTC, makew0rld commented
> It seems browsertrix gives a new cert every time i try, not sure if we should just trust all cert sha for now

Can you expand on this? A new `domainCert` every time?

Maybe instead of having a manual list of `trustedDomainFingerprints`, a better way to verify would be to use the OS's CA store (with `x509.SystemCertPool`), and just check that `domainCert` is a valid certificate chain for the `domain`, no matter who the CA is. Because if Browsertrix switches from Let's Encrypt to ZeroSSL one day, that shouldn't necessarily fail in our system. Is that possible? That might fix your problem.

Feel free to respond in Slack if that's better.

2024-06-19 15:22 UTC, makew0rld approved these changes
Looks good. Happy to merge if this is tested and working on your end. Or we can do docs in this PR too.

One thing I'll add regarding docs is we should have an example curl command that sets up Browsertrix with the webhook URL.

2024-06-19 15:22 UTC, makew0rld commented on webhook/browsertrix.go
> +		Size        int    `json:"size"`
```suggestion
		Size        int64    `json:"size"`
```

For correctness we should explicitly support file sizes above 4 GiB.

2024-06-19 16:31 UTC, williamchong commented on webhook/browsertrix.go
> +		Size        int    `json:"size"`
updated and also updated comparison

2024-06-19 16:39 UTC, williamchong commented
> Looks good. Happy to merge if this is tested and working on your end. Or we can do docs in this PR too.
> 
> One thing I'll add regarding docs is we should have an example curl command that sets up Browsertrix with the webhook URL.

Yes I have tested with actual webhook payload, will make doc in another PR

2024-06-19 19:12 UTC, makew0rld commented
Will merge once changes mentioned in Slack are integrated.

2024-06-19 21:37 UTC, williamchong commented
updated, we still need to have trust list for freetsa though

2024-06-24 13:26 UTC, merged