[preprocessor/folder] Add folder preprocessor
starlinglab/integrity-v2 pull request #6
Opened 2024-05-21 10:49 UTC by williamchong

Base on https://github.com/starlinglab/integrity-v2/pull/1
Related issue: https://github.com/starlinglab/integrity-v2/issues/2

In this PR:
- set sync folder and whitelisted extension in config
- scan directory once on start
- watches sync folder file change with fsnotify
- ignore anything that starts with `.` and ends with `.partial`
- auto calculates following attribute
  - sha256
  - md5
  - blake3
  - mimetype
  - fileSize
  - fileName
  - fileLastModified
- posts to webhook (need discussion on config of webhook server vs webhook client

In progress:
- pg integration with file status/progress

2024-05-21 17:53 UTC, makew0rld commented
Note: the code here must be reviewed after #1 is merged as it contains that diff as well.

---

> mimetype

Should be called `media_type`. Other attributes such as `fileName` should be changed to use snake case, so for example it becomes `file_name`.

2024-05-30 14:03 UTC, williamchong commented
@makew0rld rebased this PR onto current main branch

2024-05-30 19:30 UTC, makew0rld requested changes
Thanks, see comments below. Also will need you to resolve that CI failure before it can be merged.

2024-05-30 20:14 UTC, williamchong commented on preprocessor/folder/folder.go
> +						cid, err := handleNewFile(filePath)
Yes after when we introduce database in https://github.com/starlinglab/integrity-v2/pull/9

2024-05-30 20:17 UTC, williamchong commented on preprocessor/folder/folder.go
> +	"github.com/fsnotify/fsnotify"
In https://github.com/starlinglab/integrity-v2/pull/10/commits/adba73d306dba6eca3e1132aba6f901479922c9a#diff-581a5360a99f260bd4f029883f4aa1e439ab88fe3d037fdeed439357352abd51R28 i would also log subdirectory into a list for watch when walking, but indeed we can consider switching library

2024-05-30 21:09 UTC, williamchong commented on example_config.toml
> +file_extensions = ['.jpg', '.png', '.jpeg']
Can @benhylau confirm these should be in admin db?

2024-05-30 21:10 UTC, makew0rld commented on preprocessor/folder/folder.go
> +	"github.com/fsnotify/fsnotify"
The problem is we want to be aware of dynamically created subdirectories as well. One way to do this would be to keep using fsnotify, but rescan the directory every 30 mins or something, instead of on startup. I'm not sure if that's easier or better than using the other library. It's up to you.

2024-05-31 18:10 UTC, williamchong commented on preprocessor/folder/file.go
> +	mediaType := http.DetectContentType(buffer[:n])
Sure we will handle it per special file type in their own PR

2024-05-31 18:14 UTC, williamchong commented on preprocessor/folder/file.go
> +		"file_size":     fileInfo.Size(),
moved sha256, md5, blake3 and file_size into webhook

2024-05-31 18:29 UTC, williamchong commented on preprocessor/folder/folder.go
> +	"github.com/fsnotify/fsnotify"
https://github.com/starlinglab/integrity-v2/pull/6/commits/f40e1edc3398787b385aadde5bb7655f97884a07
swapped to [rjeczalik/notify](https://github.com/rjeczalik/notify)

2024-05-31 18:30 UTC, williamchong commented on example_config.toml
> +file_extensions = ['.jpg', '.png', '.jpeg']
Maybe we can handle this in the admin db PR https://github.com/starlinglab/integrity-v2/pull/10
And keep the config for this PR for now

2024-06-03 13:53 UTC, makew0rld approved these changes
Some small changes, although what I propose for file watching will require some testing to ensure thread-safety.

2024-06-03 13:53 UTC, makew0rld commented on preprocessor/folder/folder.go
> +	}
In general I think the service should fail rather than proceed with hidden defaults, let's remove this. It's good to expect the user to configure all these options beforehand. For my own testing I just have a debug version of the config file I use.

2024-06-03 13:53 UTC, makew0rld commented on preprocessor/folder/folder.go
> +			log.Println("Found: " + path)
```suggestion
			log.Println("found: " + path)
```

2024-06-03 13:53 UTC, makew0rld commented on preprocessor/folder/folder.go
> +			log.Printf("File %s uploaded to webhook with CID %s\n", filePath, cid)
```suggestion
			log.Printf("file %s uploaded to webhook with CID %s\n", filePath, cid)
```

2024-06-03 13:53 UTC, makew0rld commented on preprocessor/folder/folder.go
> +		if event == notify.Rename || event == notify.Create {
Probably everything inside this if statement should run in a goroutine instead. The `notify` docs mention that unhandled events will be dropped from the channel. So we don't want to spend a lot of time doing things that aren't reading channel events, like uploading a file in this case. Instead let's do all the processing in its own goroutine.

Note that means all the function called here like `shouldIncludeFile` and `handleNewFile` need to be thread-safe.

2024-06-03 14:30 UTC, williamchong commented on preprocessor/folder/folder.go
> +		if event == notify.Rename || event == notify.Create {
I have run `-race` with https://github.com/starlinglab/integrity-v2/pull/6/commits/efd3a0a34b971fb24a8983d202490ff59bc9794a seems I get not race condition warning for now

2024-06-03 17:22 UTC, makew0rld approved these changes
Let me know when you are ready to merge.

2024-06-03 17:31 UTC, williamchong commented
> Let me know when you are ready to merge.

Yes please merge, currently the logic is basic and I would perform more testing after we introduce db in next pr

2024-06-04 13:04 UTC, merged